spring:
  application:
    name: terrible-task-processor
  cloud:
    stream:
      bindings:
        directoryChannel:
          destination: terrible-directory-scanner
          group: terrible-directory-scanner
        output:
          destination: terrible-task-launcher

server:
  port: 0

logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG
