server:
  port: 8083

spring:
  application:
    name: terrible-task-processor
  cloud:
    stream:
      bindings:
        thumbnailChannel:
          destination: terrible-thumbnail-creator
          group: terrible-thumbnail-creator
        directoryChannel:
          destination: terrible-directory-scanner
          group: terrible-directory-scanner
        apiChannel:
          destination: terrible-api-service
          group: terrible-api-service
        apiChannelThumbnail:
          destination: terrible-api-service-thumbnail
          group: terrible-api-service
        output:
          destination: terrible-task-launcher

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
