server:
  port: 8080

spring:
  application:
    name: terrible-task-processor
  cloud:
    stream:
      bindings:
        thumbnailChannel:
          destination: terrible-thumbnail-creator
          group: terrible-thumbnail-creator
        directoryChannel:
          destination: terrible-directory-scanner
          group: terrible-directory-scanner
        output:
          destination: terrible-task-launcher
